language: php

sudo: false

branches:
  only:
    - master
    - /^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files
    - $HOME/node_modules
    - node_modules

addons:
  apt:
    packages:
      - nginx
      - subversion

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.0
  - 7.1
  - nightly

env:
  global:
    - COMPOSER_NO_INTERACTION=1
  matrix:
    - WP_VERSION=nightly
    - WP_VERSION=latest
    - WP_VERSION=4.7.3

matrix:
  allow_failures:
    - php: nightly
    - env: WP_VERSION=nightly
  fast_finish: true

before_install:
  # Disable xDebug to speed up the build unless test coverage is needed
  - if [[ $(phpenv version-name) != "nightly" ]]; then phpenv config-rm xdebug.ini; fi

  # Install helper scripts
  - travis_retry composer global require --prefer-dist --no-suggest typisttech/travis-nginx-wordpress:"^2.0"
  - export PATH=$HOME/.composer/vendor/bin:$PATH
  - tnw-install-nginx
  - tnw-install-wordpress
  - tnw-prepare-codeception

  # For grunt tasks
  - nvm install stable
  - npm update -g npm

  # Build the production plugin
  - travis_retry composer build
  # Install the medium plugin
  - wp plugin install medium --force --activate --path=/tmp/wordpress
  # Activate the plugin
  - wp plugin install ./release/remove-medium-cross-links.zip --force --activate --path=/tmp/wordpress
  # Export a dump of plugin-activated database to the _data folder
  - wp db export $TRAVIS_BUILD_DIR/tests/_data/dump.sql --path=/tmp/wordpress

install:
  - travis_retry composer install --prefer-dist --no-suggest

script:
  - vendor/bin/codecept run

before_deploy:
  - unzip -qo release/remove-medium-cross-links.zip -d build

deploy:
  - provider: releases
    api_key:
      secure: YJUOY8E0AfEWFrXHtnR9Rcn4ZxgdIDW3AC4OCpATr5vOk6Ecf+6R3z8tbqUX0//ev4MtReMUKCvdNB+eZZ+IZej+cJIptEUEig9EHDdl+nnIZKMhSrc59QGZsYQStCdTtyh/M6HNOSdTiGNdyOgIad5lwrIO0w5Nzu030ZCwWbh5rk3VETJwTRiKp3ccIU5K/uaZ1GyKGVOioRqdGKaQLtjcgbOnQTFoW1pz+xz3eeBJpYW+OV5p+9QZUSbACP8sUv/DJCrKYyoo+FtqO3tKR6Pej+TASvTg67YrrJZWTt4YOHSX2YepsOmFFvt3qf8eoKCgUwN5qSB47gGXgJDBiuUzVJ1szo3Dd0BJ2TOCIpedN3zQ6AR1BEVLXgQNHeFQPHl/QjZqokaJlaJdaIYGnl4KKtuZoqvwMjBGl6UkBVTryZo9+OT4iA20WY35RfmlTkS1Fd6whQKS3hVcLVhatHSlXnhGHdVTTD1UN912NMnIeHKQCIgnnJFKIO5I5uJZcZS2+blcu4viwEWScVgd71lys/thlUsTf7pbMDFkLGReL4Oz+fqel1XfU5mPO/42/1EaC2KY7OKVepM26a7ZzPtzGm/N7ixZ3emqi1+TFWeAklWNIPQ2EXkt882LYJDyjbDQ2wmoA92DXgk3t0F2v5KQeSConu4JiPhLP98uVOo=
    file: release/remove-medium-cross-links.zip
    skip_cleanup: true
    on:
      condition: "$WP_VERSION = latest"
      php: 7.1
      tags: true
      repo: TypistTech/remove-medium-cross-links
  - provider: wordpress-plugin
    edge:
      source: TypistTech/dpl
      branch: add-wordpress-plugin-deployment
    slug: remove-medium-cross-links
    username: tangrufus
    build_dir: build
    assets_dir: assets
    skip_cleanup: true
    on:
      condition: "$WP_VERSION = latest"
      php: 7.0
      tags: true
      repo: TypistTech/remove-medium-cross-links
